version: '3.8'

x-server-common: &server-common
  build:
    dockerfile: ./server/Dockerfile
    context: .
  environment:
    DATABASE_URI: postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE}
    REDIS_URI: redis://redis:6379/1
    SECRET_KEY: ${SECRET_KEY}
  env_file:
    - .env
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy


services:
  server:
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    <<: *server-common

  db:
    image: postgres:16.2-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 10s
      retries: 40

  redis:
    image: redis:7.2.4-alpine
    restart: always
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 2s
      timeout: 10s
      retries: 40
