version: '3.8'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    environment:
      POSTGRES_URI: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URI: redis://redis:6379/1
      SECRET_KEY: ${SECRET_KEY}
    command: 
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
      ]
    ports:
      - 8000:8000
      - 5678:5678

    env_file:
      - .env
    volumes:
      - ./server:/server
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 10s
      retries: 40

  redis:
    image: redis:7.2.4-alpine
    restart: always
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 5s
      timeout: 10s
      retries: 40
