version: '3.8'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    environment:
      POSTGRES_URI: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 10s
      retries: 40
