version: '3.8'

volumes:
  server:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/server
  media:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/media
  static:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/static

x-server-common: &server-common
  build:
    dockerfile: ./server/Dockerfile
    context: .
  volumes:
    - server:/server
    - media:/server/media
    - static:/server/static
  env_file:
    - .env
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  server:
    command: uvicorn config.fastapi:fastapi --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    <<: *server-common

  taskiq:
    command: taskiq worker config.taskiq:broker --fs-discover --reload --tasks-pattern **/tasks/*.py
    <<: *server-common

  db:
    image: postgres:16.2-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 10s
      retries: 40

  redis:
    image: redis:7.2.4-alpine
    restart: always
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 2s
      timeout: 10s
      retries: 40
