"""empty message

Revision ID: 13aeb5b2c8cc
Revises: f4ea538f33a2
Create Date: 2024-04-12 21:25:31.185991

"""
from alembic import op
import sqlalchemy as sa


revision = '13aeb5b2c8cc'
down_revision = 'f4ea538f33a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###